//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:ubl:codelist:ChannelCode:1:0")
package oasis.names.tc.ubl.codelist.channelcode._1._0;
