//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SFTIPartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIPartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PartyIdentification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PartyName"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}Address"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PartyTaxScheme" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}Contact" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIPartyType", propOrder = {
    "partyIdentification",
    "partyName",
    "address",
    "partyTaxScheme",
    "contact"
})
public class SFTIPartyType {

    @XmlElement(name = "PartyIdentification")
    protected List<SFTIPartyIdentificationType> partyIdentification;
    @XmlElement(name = "PartyName", required = true)
    protected SFTIPartyNameType partyName;
    @XmlElement(name = "Address", required = true)
    protected SFTIAddressType address;
    @XmlElement(name = "PartyTaxScheme")
    protected List<SFTIPartyTaxSchemeType> partyTaxScheme;
    @XmlElement(name = "Contact")
    protected SFTIContactType contact;

    /**
     * Gets the value of the partyIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIPartyIdentificationType }
     * 
     * 
     */
    public List<SFTIPartyIdentificationType> getPartyIdentification() {
        if (partyIdentification == null) {
            partyIdentification = new ArrayList<SFTIPartyIdentificationType>();
        }
        return this.partyIdentification;
    }

    /**
     * Gets the value of the partyName property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIPartyNameType }
     *     
     */
    public SFTIPartyNameType getPartyName() {
        return partyName;
    }

    /**
     * Sets the value of the partyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIPartyNameType }
     *     
     */
    public void setPartyName(SFTIPartyNameType value) {
        this.partyName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIAddressType }
     *     
     */
    public SFTIAddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIAddressType }
     *     
     */
    public void setAddress(SFTIAddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the partyTaxScheme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyTaxScheme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyTaxScheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIPartyTaxSchemeType }
     * 
     * 
     */
    public List<SFTIPartyTaxSchemeType> getPartyTaxScheme() {
        if (partyTaxScheme == null) {
            partyTaxScheme = new ArrayList<SFTIPartyTaxSchemeType>();
        }
        return this.partyTaxScheme;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIContactType }
     *     
     */
    public SFTIContactType getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIContactType }
     *     
     */
    public void setContact(SFTIContactType value) {
        this.contact = value;
    }

}
