//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sfti.commonaggregatecomponents._1._0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Language_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Language");
    private final static QName _DeliveryTerms_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "DeliveryTerms");
    private final static QName _OrderLineReference_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "OrderLineReference");
    private final static QName _OrderContact_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "OrderContact");
    private final static QName _Period_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Period");
    private final static QName _SellersItemIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "SellersItemIdentification");
    private final static QName _PaymentTerms_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PaymentTerms");
    private final static QName _Country_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Country");
    private final static QName _PartyTaxScheme_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PartyTaxScheme");
    private final static QName _Item_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Item");
    private final static QName _PaymentMeans_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PaymentMeans");
    private final static QName _Payment_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Payment");
    private final static QName _BuyerParty_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "BuyerParty");
    private final static QName _OrderReference_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "OrderReference");
    private final static QName _FinancialInstitution_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "FinancialInstitution");
    private final static QName _AllowanceCharge_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "AllowanceCharge");
    private final static QName _LineReference_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "LineReference");
    private final static QName _Delivery_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Delivery");
    private final static QName _TaxScheme_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "TaxScheme");
    private final static QName _TaxCategory_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "TaxCategory");
    private final static QName _DespatchLineReference_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "DespatchLineReference");
    private final static QName _PartyIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PartyIdentification");
    private final static QName _ExchangeRate_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "ExchangeRate");
    private final static QName _DocumentReference_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "DocumentReference");
    private final static QName _StandardItemIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "StandardItemIdentification");
    private final static QName _PartyName_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PartyName");
    private final static QName _Address_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Address");
    private final static QName _AdditionalItemIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "AdditionalItemIdentification");
    private final static QName _ItemIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "ItemIdentification");
    private final static QName _BasePrice_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "BasePrice");
    private final static QName _TaxSubTotal_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "TaxSubTotal");
    private final static QName _LocationCoordinate_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "LocationCoordinate");
    private final static QName _JurisdictionAddress_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "JurisdictionAddress");
    private final static QName _AddressLine_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "AddressLine");
    private final static QName _RegistrationAddress_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "RegistrationAddress");
    private final static QName _Party_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Party");
    private final static QName _Contact_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "Contact");
    private final static QName _AccountsContact_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "AccountsContact");
    private final static QName _BuyersItemIdentification_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "BuyersItemIdentification");
    private final static QName _TaxTotal_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "TaxTotal");
    private final static QName _LegalTotal_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "LegalTotal");
    private final static QName _InvoiceLine_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "InvoiceLine");
    private final static QName _DeliveryAddress_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "DeliveryAddress");
    private final static QName _FinancialInstitutionBranch_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "FinancialInstitutionBranch");
    private final static QName _PayeeFinancialAccount_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "PayeeFinancialAccount");
    private final static QName _SellerParty_QNAME = new QName("urn:sfti:CommonAggregateComponents:1:0", "SellerParty");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sfti.commonaggregatecomponents._1._0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SFTIAddressType }
     * 
     */
    public SFTIAddressType createSFTIAddressType() {
        return new SFTIAddressType();
    }

    /**
     * Create an instance of {@link SFTIDeliveryTermsType }
     * 
     */
    public SFTIDeliveryTermsType createSFTIDeliveryTermsType() {
        return new SFTIDeliveryTermsType();
    }

    /**
     * Create an instance of {@link SFTISimpleIdentifierType }
     * 
     */
    public SFTISimpleIdentifierType createSFTISimpleIdentifierType() {
        return new SFTISimpleIdentifierType();
    }

    /**
     * Create an instance of {@link SFTIAllowanceChargeType }
     * 
     */
    public SFTIAllowanceChargeType createSFTIAllowanceChargeType() {
        return new SFTIAllowanceChargeType();
    }

    /**
     * Create an instance of {@link SFTIPartyNameType }
     * 
     */
    public SFTIPartyNameType createSFTIPartyNameType() {
        return new SFTIPartyNameType();
    }

    /**
     * Create an instance of {@link SFTIInvoiceLineDeliveryType }
     * 
     */
    public SFTIInvoiceLineDeliveryType createSFTIInvoiceLineDeliveryType() {
        return new SFTIInvoiceLineDeliveryType();
    }

    /**
     * Create an instance of {@link SFTIDeliveryType }
     * 
     */
    public SFTIDeliveryType createSFTIDeliveryType() {
        return new SFTIDeliveryType();
    }

    /**
     * Create an instance of {@link SFTIPaymentType }
     * 
     */
    public SFTIPaymentType createSFTIPaymentType() {
        return new SFTIPaymentType();
    }

    /**
     * Create an instance of {@link SFTIPaymentTermsType }
     * 
     */
    public SFTIPaymentTermsType createSFTIPaymentTermsType() {
        return new SFTIPaymentTermsType();
    }

    /**
     * Create an instance of {@link SFTIPeriodType }
     * 
     */
    public SFTIPeriodType createSFTIPeriodType() {
        return new SFTIPeriodType();
    }

    /**
     * Create an instance of {@link SFTITaxTotalType }
     * 
     */
    public SFTITaxTotalType createSFTITaxTotalType() {
        return new SFTITaxTotalType();
    }

    /**
     * Create an instance of {@link SFTISellerPartyType }
     * 
     */
    public SFTISellerPartyType createSFTISellerPartyType() {
        return new SFTISellerPartyType();
    }

    /**
     * Create an instance of {@link SFTIPaymentMeansType }
     * 
     */
    public SFTIPaymentMeansType createSFTIPaymentMeansType() {
        return new SFTIPaymentMeansType();
    }

    /**
     * Create an instance of {@link SFTIItemIdentificationType }
     * 
     */
    public SFTIItemIdentificationType createSFTIItemIdentificationType() {
        return new SFTIItemIdentificationType();
    }

    /**
     * Create an instance of {@link SFTITaxSchemeType }
     * 
     */
    public SFTITaxSchemeType createSFTITaxSchemeType() {
        return new SFTITaxSchemeType();
    }

    /**
     * Create an instance of {@link SFTIPartyIdentificationType }
     * 
     */
    public SFTIPartyIdentificationType createSFTIPartyIdentificationType() {
        return new SFTIPartyIdentificationType();
    }

    /**
     * Create an instance of {@link SFTICountryType }
     * 
     */
    public SFTICountryType createSFTICountryType() {
        return new SFTICountryType();
    }

    /**
     * Create an instance of {@link SFTITaxSubTotalType }
     * 
     */
    public SFTITaxSubTotalType createSFTITaxSubTotalType() {
        return new SFTITaxSubTotalType();
    }

    /**
     * Create an instance of {@link SFTILegalTotalType }
     * 
     */
    public SFTILegalTotalType createSFTILegalTotalType() {
        return new SFTILegalTotalType();
    }

    /**
     * Create an instance of {@link SFTIContactType }
     * 
     */
    public SFTIContactType createSFTIContactType() {
        return new SFTIContactType();
    }

    /**
     * Create an instance of {@link SFTIOrderReferenceType }
     * 
     */
    public SFTIOrderReferenceType createSFTIOrderReferenceType() {
        return new SFTIOrderReferenceType();
    }

    /**
     * Create an instance of {@link SFTILineReferenceType }
     * 
     */
    public SFTILineReferenceType createSFTILineReferenceType() {
        return new SFTILineReferenceType();
    }

    /**
     * Create an instance of {@link SFTIItemType }
     * 
     */
    public SFTIItemType createSFTIItemType() {
        return new SFTIItemType();
    }

    /**
     * Create an instance of {@link SFTIFinancialInstitutionType }
     * 
     */
    public SFTIFinancialInstitutionType createSFTIFinancialInstitutionType() {
        return new SFTIFinancialInstitutionType();
    }

    /**
     * Create an instance of {@link SFTIPartyType }
     * 
     */
    public SFTIPartyType createSFTIPartyType() {
        return new SFTIPartyType();
    }

    /**
     * Create an instance of {@link SFTIInvoiceLineType }
     * 
     */
    public SFTIInvoiceLineType createSFTIInvoiceLineType() {
        return new SFTIInvoiceLineType();
    }

    /**
     * Create an instance of {@link SFTIPartyTaxSchemeType }
     * 
     */
    public SFTIPartyTaxSchemeType createSFTIPartyTaxSchemeType() {
        return new SFTIPartyTaxSchemeType();
    }

    /**
     * Create an instance of {@link SFTILocationCoordinateType }
     * 
     */
    public SFTILocationCoordinateType createSFTILocationCoordinateType() {
        return new SFTILocationCoordinateType();
    }

    /**
     * Create an instance of {@link SFTIAddressLineType }
     * 
     */
    public SFTIAddressLineType createSFTIAddressLineType() {
        return new SFTIAddressLineType();
    }

    /**
     * Create an instance of {@link SFTIExchangeRateType }
     * 
     */
    public SFTIExchangeRateType createSFTIExchangeRateType() {
        return new SFTIExchangeRateType();
    }

    /**
     * Create an instance of {@link SFTIBranchType }
     * 
     */
    public SFTIBranchType createSFTIBranchType() {
        return new SFTIBranchType();
    }

    /**
     * Create an instance of {@link SFTIDocumentReferenceType }
     * 
     */
    public SFTIDocumentReferenceType createSFTIDocumentReferenceType() {
        return new SFTIDocumentReferenceType();
    }

    /**
     * Create an instance of {@link SFTIDespatchLineType }
     * 
     */
    public SFTIDespatchLineType createSFTIDespatchLineType() {
        return new SFTIDespatchLineType();
    }

    /**
     * Create an instance of {@link SFTIBuyerPartyType }
     * 
     */
    public SFTIBuyerPartyType createSFTIBuyerPartyType() {
        return new SFTIBuyerPartyType();
    }

    /**
     * Create an instance of {@link SFTIFinancialAccountType }
     * 
     */
    public SFTIFinancialAccountType createSFTIFinancialAccountType() {
        return new SFTIFinancialAccountType();
    }

    /**
     * Create an instance of {@link SFTITaxCategoryType }
     * 
     */
    public SFTITaxCategoryType createSFTITaxCategoryType() {
        return new SFTITaxCategoryType();
    }

    /**
     * Create an instance of {@link SFTIInvoiceLineAllowanceCharge }
     * 
     */
    public SFTIInvoiceLineAllowanceCharge createSFTIInvoiceLineAllowanceCharge() {
        return new SFTIInvoiceLineAllowanceCharge();
    }

    /**
     * Create an instance of {@link SFTIOrderLineReferenceType }
     * 
     */
    public SFTIOrderLineReferenceType createSFTIOrderLineReferenceType() {
        return new SFTIOrderLineReferenceType();
    }

    /**
     * Create an instance of {@link SFTILanguageType }
     * 
     */
    public SFTILanguageType createSFTILanguageType() {
        return new SFTILanguageType();
    }

    /**
     * Create an instance of {@link SFTIBasePriceType }
     * 
     */
    public SFTIBasePriceType createSFTIBasePriceType() {
        return new SFTIBasePriceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTILanguageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Language")
    public JAXBElement<SFTILanguageType> createLanguage(SFTILanguageType value) {
        return new JAXBElement<SFTILanguageType>(_Language_QNAME, SFTILanguageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIDeliveryTermsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "DeliveryTerms")
    public JAXBElement<SFTIDeliveryTermsType> createDeliveryTerms(SFTIDeliveryTermsType value) {
        return new JAXBElement<SFTIDeliveryTermsType>(_DeliveryTerms_QNAME, SFTIDeliveryTermsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIOrderLineReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "OrderLineReference")
    public JAXBElement<SFTIOrderLineReferenceType> createOrderLineReference(SFTIOrderLineReferenceType value) {
        return new JAXBElement<SFTIOrderLineReferenceType>(_OrderLineReference_QNAME, SFTIOrderLineReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "OrderContact")
    public JAXBElement<SFTIContactType> createOrderContact(SFTIContactType value) {
        return new JAXBElement<SFTIContactType>(_OrderContact_QNAME, SFTIContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPeriodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Period")
    public JAXBElement<SFTIPeriodType> createPeriod(SFTIPeriodType value) {
        return new JAXBElement<SFTIPeriodType>(_Period_QNAME, SFTIPeriodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "SellersItemIdentification")
    public JAXBElement<SFTIItemIdentificationType> createSellersItemIdentification(SFTIItemIdentificationType value) {
        return new JAXBElement<SFTIItemIdentificationType>(_SellersItemIdentification_QNAME, SFTIItemIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPaymentTermsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PaymentTerms")
    public JAXBElement<SFTIPaymentTermsType> createPaymentTerms(SFTIPaymentTermsType value) {
        return new JAXBElement<SFTIPaymentTermsType>(_PaymentTerms_QNAME, SFTIPaymentTermsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTICountryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Country")
    public JAXBElement<SFTICountryType> createCountry(SFTICountryType value) {
        return new JAXBElement<SFTICountryType>(_Country_QNAME, SFTICountryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPartyTaxSchemeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PartyTaxScheme")
    public JAXBElement<SFTIPartyTaxSchemeType> createPartyTaxScheme(SFTIPartyTaxSchemeType value) {
        return new JAXBElement<SFTIPartyTaxSchemeType>(_PartyTaxScheme_QNAME, SFTIPartyTaxSchemeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Item")
    public JAXBElement<SFTIItemType> createItem(SFTIItemType value) {
        return new JAXBElement<SFTIItemType>(_Item_QNAME, SFTIItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPaymentMeansType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PaymentMeans")
    public JAXBElement<SFTIPaymentMeansType> createPaymentMeans(SFTIPaymentMeansType value) {
        return new JAXBElement<SFTIPaymentMeansType>(_PaymentMeans_QNAME, SFTIPaymentMeansType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPaymentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Payment")
    public JAXBElement<SFTIPaymentType> createPayment(SFTIPaymentType value) {
        return new JAXBElement<SFTIPaymentType>(_Payment_QNAME, SFTIPaymentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIBuyerPartyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "BuyerParty")
    public JAXBElement<SFTIBuyerPartyType> createBuyerParty(SFTIBuyerPartyType value) {
        return new JAXBElement<SFTIBuyerPartyType>(_BuyerParty_QNAME, SFTIBuyerPartyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIOrderReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "OrderReference")
    public JAXBElement<SFTIOrderReferenceType> createOrderReference(SFTIOrderReferenceType value) {
        return new JAXBElement<SFTIOrderReferenceType>(_OrderReference_QNAME, SFTIOrderReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIFinancialInstitutionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "FinancialInstitution")
    public JAXBElement<SFTIFinancialInstitutionType> createFinancialInstitution(SFTIFinancialInstitutionType value) {
        return new JAXBElement<SFTIFinancialInstitutionType>(_FinancialInstitution_QNAME, SFTIFinancialInstitutionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIInvoiceLineAllowanceCharge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "AllowanceCharge")
    public JAXBElement<SFTIInvoiceLineAllowanceCharge> createAllowanceCharge(SFTIInvoiceLineAllowanceCharge value) {
        return new JAXBElement<SFTIInvoiceLineAllowanceCharge>(_AllowanceCharge_QNAME, SFTIInvoiceLineAllowanceCharge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTILineReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "LineReference")
    public JAXBElement<SFTILineReferenceType> createLineReference(SFTILineReferenceType value) {
        return new JAXBElement<SFTILineReferenceType>(_LineReference_QNAME, SFTILineReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIDeliveryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Delivery")
    public JAXBElement<SFTIDeliveryType> createDelivery(SFTIDeliveryType value) {
        return new JAXBElement<SFTIDeliveryType>(_Delivery_QNAME, SFTIDeliveryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTITaxSchemeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "TaxScheme")
    public JAXBElement<SFTITaxSchemeType> createTaxScheme(SFTITaxSchemeType value) {
        return new JAXBElement<SFTITaxSchemeType>(_TaxScheme_QNAME, SFTITaxSchemeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTITaxCategoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "TaxCategory")
    public JAXBElement<SFTITaxCategoryType> createTaxCategory(SFTITaxCategoryType value) {
        return new JAXBElement<SFTITaxCategoryType>(_TaxCategory_QNAME, SFTITaxCategoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTILineReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "DespatchLineReference")
    public JAXBElement<SFTILineReferenceType> createDespatchLineReference(SFTILineReferenceType value) {
        return new JAXBElement<SFTILineReferenceType>(_DespatchLineReference_QNAME, SFTILineReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPartyIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PartyIdentification")
    public JAXBElement<SFTIPartyIdentificationType> createPartyIdentification(SFTIPartyIdentificationType value) {
        return new JAXBElement<SFTIPartyIdentificationType>(_PartyIdentification_QNAME, SFTIPartyIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIExchangeRateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "ExchangeRate")
    public JAXBElement<SFTIExchangeRateType> createExchangeRate(SFTIExchangeRateType value) {
        return new JAXBElement<SFTIExchangeRateType>(_ExchangeRate_QNAME, SFTIExchangeRateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIDocumentReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "DocumentReference")
    public JAXBElement<SFTIDocumentReferenceType> createDocumentReference(SFTIDocumentReferenceType value) {
        return new JAXBElement<SFTIDocumentReferenceType>(_DocumentReference_QNAME, SFTIDocumentReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "StandardItemIdentification")
    public JAXBElement<SFTIItemIdentificationType> createStandardItemIdentification(SFTIItemIdentificationType value) {
        return new JAXBElement<SFTIItemIdentificationType>(_StandardItemIdentification_QNAME, SFTIItemIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPartyNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PartyName")
    public JAXBElement<SFTIPartyNameType> createPartyName(SFTIPartyNameType value) {
        return new JAXBElement<SFTIPartyNameType>(_PartyName_QNAME, SFTIPartyNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Address")
    public JAXBElement<SFTIAddressType> createAddress(SFTIAddressType value) {
        return new JAXBElement<SFTIAddressType>(_Address_QNAME, SFTIAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "AdditionalItemIdentification")
    public JAXBElement<SFTIItemIdentificationType> createAdditionalItemIdentification(SFTIItemIdentificationType value) {
        return new JAXBElement<SFTIItemIdentificationType>(_AdditionalItemIdentification_QNAME, SFTIItemIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "ItemIdentification")
    public JAXBElement<SFTIItemIdentificationType> createItemIdentification(SFTIItemIdentificationType value) {
        return new JAXBElement<SFTIItemIdentificationType>(_ItemIdentification_QNAME, SFTIItemIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIBasePriceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "BasePrice")
    public JAXBElement<SFTIBasePriceType> createBasePrice(SFTIBasePriceType value) {
        return new JAXBElement<SFTIBasePriceType>(_BasePrice_QNAME, SFTIBasePriceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTITaxSubTotalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "TaxSubTotal")
    public JAXBElement<SFTITaxSubTotalType> createTaxSubTotal(SFTITaxSubTotalType value) {
        return new JAXBElement<SFTITaxSubTotalType>(_TaxSubTotal_QNAME, SFTITaxSubTotalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTILocationCoordinateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "LocationCoordinate")
    public JAXBElement<SFTILocationCoordinateType> createLocationCoordinate(SFTILocationCoordinateType value) {
        return new JAXBElement<SFTILocationCoordinateType>(_LocationCoordinate_QNAME, SFTILocationCoordinateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "JurisdictionAddress")
    public JAXBElement<SFTIAddressType> createJurisdictionAddress(SFTIAddressType value) {
        return new JAXBElement<SFTIAddressType>(_JurisdictionAddress_QNAME, SFTIAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIAddressLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "AddressLine")
    public JAXBElement<SFTIAddressLineType> createAddressLine(SFTIAddressLineType value) {
        return new JAXBElement<SFTIAddressLineType>(_AddressLine_QNAME, SFTIAddressLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "RegistrationAddress")
    public JAXBElement<SFTIAddressType> createRegistrationAddress(SFTIAddressType value) {
        return new JAXBElement<SFTIAddressType>(_RegistrationAddress_QNAME, SFTIAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIPartyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Party")
    public JAXBElement<SFTIPartyType> createParty(SFTIPartyType value) {
        return new JAXBElement<SFTIPartyType>(_Party_QNAME, SFTIPartyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "Contact")
    public JAXBElement<SFTIContactType> createContact(SFTIContactType value) {
        return new JAXBElement<SFTIContactType>(_Contact_QNAME, SFTIContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "AccountsContact")
    public JAXBElement<SFTIContactType> createAccountsContact(SFTIContactType value) {
        return new JAXBElement<SFTIContactType>(_AccountsContact_QNAME, SFTIContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIItemIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "BuyersItemIdentification")
    public JAXBElement<SFTIItemIdentificationType> createBuyersItemIdentification(SFTIItemIdentificationType value) {
        return new JAXBElement<SFTIItemIdentificationType>(_BuyersItemIdentification_QNAME, SFTIItemIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTITaxTotalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "TaxTotal")
    public JAXBElement<SFTITaxTotalType> createTaxTotal(SFTITaxTotalType value) {
        return new JAXBElement<SFTITaxTotalType>(_TaxTotal_QNAME, SFTITaxTotalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTILegalTotalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "LegalTotal")
    public JAXBElement<SFTILegalTotalType> createLegalTotal(SFTILegalTotalType value) {
        return new JAXBElement<SFTILegalTotalType>(_LegalTotal_QNAME, SFTILegalTotalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIInvoiceLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "InvoiceLine")
    public JAXBElement<SFTIInvoiceLineType> createInvoiceLine(SFTIInvoiceLineType value) {
        return new JAXBElement<SFTIInvoiceLineType>(_InvoiceLine_QNAME, SFTIInvoiceLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "DeliveryAddress")
    public JAXBElement<SFTIAddressType> createDeliveryAddress(SFTIAddressType value) {
        return new JAXBElement<SFTIAddressType>(_DeliveryAddress_QNAME, SFTIAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIBranchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "FinancialInstitutionBranch")
    public JAXBElement<SFTIBranchType> createFinancialInstitutionBranch(SFTIBranchType value) {
        return new JAXBElement<SFTIBranchType>(_FinancialInstitutionBranch_QNAME, SFTIBranchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTIFinancialAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "PayeeFinancialAccount")
    public JAXBElement<SFTIFinancialAccountType> createPayeeFinancialAccount(SFTIFinancialAccountType value) {
        return new JAXBElement<SFTIFinancialAccountType>(_PayeeFinancialAccount_QNAME, SFTIFinancialAccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SFTISellerPartyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:sfti:CommonAggregateComponents:1:0", name = "SellerParty")
    public JAXBElement<SFTISellerPartyType> createSellerParty(SFTISellerPartyType value) {
        return new JAXBElement<SFTISellerPartyType>(_SellerParty_QNAME, SFTISellerPartyType.class, null, value);
    }

}
