//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SFTIBranchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIBranchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}FinancialInstitution" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIBranchType", propOrder = {
    "financialInstitution"
})
public class SFTIBranchType {

    @XmlElement(name = "FinancialInstitution")
    protected SFTIFinancialInstitutionType financialInstitution;

    /**
     * Gets the value of the financialInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIFinancialInstitutionType }
     *     
     */
    public SFTIFinancialInstitutionType getFinancialInstitution() {
        return financialInstitution;
    }

    /**
     * Sets the value of the financialInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIFinancialInstitutionType }
     *     
     */
    public void setFinancialInstitution(SFTIFinancialInstitutionType value) {
        this.financialInstitution = value;
    }

}
