//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.codelist.currencycode._1._0.CurrencyCodeType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.CalculationRateType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.CurrencyBaseRateType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.DateType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.UnitBaseRateType;


/**
 * <p>Java class for SFTIExchangeRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIExchangeRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceCurrencyCode" type="{urn:oasis:names:tc:ubl:codelist:CurrencyCode:1:0}CurrencyCodeType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}SourceCurrencyBaseRate" minOccurs="0"/>
 *         &lt;element name="TargetCurrencyCode" type="{urn:oasis:names:tc:ubl:codelist:CurrencyCode:1:0}CurrencyCodeType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}TargetUnitBaseRate" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}CalculationRate" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}Date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIExchangeRateType", propOrder = {
    "sourceCurrencyCode",
    "sourceCurrencyBaseRate",
    "targetCurrencyCode",
    "targetUnitBaseRate",
    "calculationRate",
    "date"
})
public class SFTIExchangeRateType {

    @XmlElement(name = "SourceCurrencyCode", required = true)
    protected CurrencyCodeType sourceCurrencyCode;
    @XmlElement(name = "SourceCurrencyBaseRate", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected CurrencyBaseRateType sourceCurrencyBaseRate;
    @XmlElement(name = "TargetCurrencyCode", required = true)
    protected CurrencyCodeType targetCurrencyCode;
    @XmlElement(name = "TargetUnitBaseRate", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected UnitBaseRateType targetUnitBaseRate;
    @XmlElement(name = "CalculationRate", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected CalculationRateType calculationRate;
    @XmlElement(name = "Date", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected DateType date;

    /**
     * Gets the value of the sourceCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getSourceCurrencyCode() {
        return sourceCurrencyCode;
    }

    /**
     * Sets the value of the sourceCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setSourceCurrencyCode(CurrencyCodeType value) {
        this.sourceCurrencyCode = value;
    }

    /**
     * Gets the value of the sourceCurrencyBaseRate property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyBaseRateType }
     *     
     */
    public CurrencyBaseRateType getSourceCurrencyBaseRate() {
        return sourceCurrencyBaseRate;
    }

    /**
     * Sets the value of the sourceCurrencyBaseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyBaseRateType }
     *     
     */
    public void setSourceCurrencyBaseRate(CurrencyBaseRateType value) {
        this.sourceCurrencyBaseRate = value;
    }

    /**
     * Gets the value of the targetCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getTargetCurrencyCode() {
        return targetCurrencyCode;
    }

    /**
     * Sets the value of the targetCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setTargetCurrencyCode(CurrencyCodeType value) {
        this.targetCurrencyCode = value;
    }

    /**
     * Gets the value of the targetUnitBaseRate property.
     * 
     * @return
     *     possible object is
     *     {@link UnitBaseRateType }
     *     
     */
    public UnitBaseRateType getTargetUnitBaseRate() {
        return targetUnitBaseRate;
    }

    /**
     * Sets the value of the targetUnitBaseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitBaseRateType }
     *     
     */
    public void setTargetUnitBaseRate(UnitBaseRateType value) {
        this.targetUnitBaseRate = value;
    }

    /**
     * Gets the value of the calculationRate property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationRateType }
     *     
     */
    public CalculationRateType getCalculationRate() {
        return calculationRate;
    }

    /**
     * Sets the value of the calculationRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationRateType }
     *     
     */
    public void setCalculationRate(CalculationRateType value) {
        this.calculationRate = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate(DateType value) {
        this.date = value;
    }

}
