//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ExtensionAmountType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.NoteType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.QuantityType;


/**
 * <p>Java class for SFTIInvoiceLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIInvoiceLineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{urn:sfti:CommonAggregateComponents:1:0}SFTISimpleIdentifierType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}InvoicedQuantity" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}LineExtensionAmount"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}Note" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}OrderLineReference" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}DespatchLineReference" minOccurs="0"/>
 *         &lt;element name="Delivery" type="{urn:sfti:CommonAggregateComponents:1:0}SFTIInvoiceLineDeliveryType" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}AllowanceCharge" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}Item"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIInvoiceLineType", propOrder = {
    "id",
    "invoicedQuantity",
    "lineExtensionAmount",
    "note",
    "orderLineReference",
    "despatchLineReference",
    "delivery",
    "allowanceCharge",
    "item"
})
public class SFTIInvoiceLineType {

    @XmlElement(name = "ID", required = true)
    protected SFTISimpleIdentifierType id;
    @XmlElement(name = "InvoicedQuantity", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected QuantityType invoicedQuantity;
    @XmlElement(name = "LineExtensionAmount", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0", required = true)
    protected ExtensionAmountType lineExtensionAmount;
    @XmlElement(name = "Note", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected NoteType note;
    @XmlElement(name = "OrderLineReference")
    protected SFTIOrderLineReferenceType orderLineReference;
    @XmlElement(name = "DespatchLineReference")
    protected SFTILineReferenceType despatchLineReference;
    @XmlElement(name = "Delivery")
    protected SFTIInvoiceLineDeliveryType delivery;
    @XmlElement(name = "AllowanceCharge")
    protected SFTIInvoiceLineAllowanceCharge allowanceCharge;
    @XmlElement(name = "Item", required = true)
    protected SFTIItemType item;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link SFTISimpleIdentifierType }
     *     
     */
    public SFTISimpleIdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTISimpleIdentifierType }
     *     
     */
    public void setID(SFTISimpleIdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the invoicedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getInvoicedQuantity() {
        return invoicedQuantity;
    }

    /**
     * Sets the value of the invoicedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setInvoicedQuantity(QuantityType value) {
        this.invoicedQuantity = value;
    }

    /**
     * Gets the value of the lineExtensionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionAmountType }
     *     
     */
    public ExtensionAmountType getLineExtensionAmount() {
        return lineExtensionAmount;
    }

    /**
     * Sets the value of the lineExtensionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionAmountType }
     *     
     */
    public void setLineExtensionAmount(ExtensionAmountType value) {
        this.lineExtensionAmount = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setNote(NoteType value) {
        this.note = value;
    }

    /**
     * Gets the value of the orderLineReference property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIOrderLineReferenceType }
     *     
     */
    public SFTIOrderLineReferenceType getOrderLineReference() {
        return orderLineReference;
    }

    /**
     * Sets the value of the orderLineReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIOrderLineReferenceType }
     *     
     */
    public void setOrderLineReference(SFTIOrderLineReferenceType value) {
        this.orderLineReference = value;
    }

    /**
     * Gets the value of the despatchLineReference property.
     * 
     * @return
     *     possible object is
     *     {@link SFTILineReferenceType }
     *     
     */
    public SFTILineReferenceType getDespatchLineReference() {
        return despatchLineReference;
    }

    /**
     * Sets the value of the despatchLineReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTILineReferenceType }
     *     
     */
    public void setDespatchLineReference(SFTILineReferenceType value) {
        this.despatchLineReference = value;
    }

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIInvoiceLineDeliveryType }
     *     
     */
    public SFTIInvoiceLineDeliveryType getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIInvoiceLineDeliveryType }
     *     
     */
    public void setDelivery(SFTIInvoiceLineDeliveryType value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the allowanceCharge property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIInvoiceLineAllowanceCharge }
     *     
     */
    public SFTIInvoiceLineAllowanceCharge getAllowanceCharge() {
        return allowanceCharge;
    }

    /**
     * Sets the value of the allowanceCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIInvoiceLineAllowanceCharge }
     *     
     */
    public void setAllowanceCharge(SFTIInvoiceLineAllowanceCharge value) {
        this.allowanceCharge = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIItemType }
     *     
     */
    public SFTIItemType getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIItemType }
     *     
     */
    public void setItem(SFTIItemType value) {
        this.item = value;
    }

}
