//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.codelist.allowancechargereasoncode._1._0.AllowanceChargeReasonCodeType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.AmountType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ChargeIndicatorType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.MultiplierFactorNumericType;


/**
 * <p>Java class for SFTIAllowanceChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIAllowanceChargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}ChargeIndicator"/>
 *         &lt;element name="ReasonCode" type="{urn:oasis:names:tc:ubl:codelist:AllowanceChargeReasonCode:1:0}AllowanceChargeReasonCodeType" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}MultiplierFactorNumeric" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}Amount"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}TaxCategory" maxOccurs="unbounded"/>
 *         &lt;element name="AllowanceChargeBaseAmount" type="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIAllowanceChargeType", propOrder = {
    "chargeIndicator",
    "reasonCode",
    "multiplierFactorNumeric",
    "amount",
    "taxCategory",
    "allowanceChargeBaseAmount"
})
public class SFTIAllowanceChargeType {

    @XmlElement(name = "ChargeIndicator", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0", required = true)
    protected ChargeIndicatorType chargeIndicator;
    @XmlElement(name = "ReasonCode")
    protected AllowanceChargeReasonCodeType reasonCode;
    @XmlElement(name = "MultiplierFactorNumeric", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected MultiplierFactorNumericType multiplierFactorNumeric;
    @XmlElement(name = "Amount", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0", required = true)
    protected AmountType amount;
    @XmlElement(name = "TaxCategory", required = true)
    protected List<SFTITaxCategoryType> taxCategory;
    @XmlElement(name = "AllowanceChargeBaseAmount")
    protected AmountType allowanceChargeBaseAmount;

    /**
     * Gets the value of the chargeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public ChargeIndicatorType getChargeIndicator() {
        return chargeIndicator;
    }

    /**
     * Sets the value of the chargeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public void setChargeIndicator(ChargeIndicatorType value) {
        this.chargeIndicator = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link AllowanceChargeReasonCodeType }
     *     
     */
    public AllowanceChargeReasonCodeType getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowanceChargeReasonCodeType }
     *     
     */
    public void setReasonCode(AllowanceChargeReasonCodeType value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the multiplierFactorNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link MultiplierFactorNumericType }
     *     
     */
    public MultiplierFactorNumericType getMultiplierFactorNumeric() {
        return multiplierFactorNumeric;
    }

    /**
     * Sets the value of the multiplierFactorNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiplierFactorNumericType }
     *     
     */
    public void setMultiplierFactorNumeric(MultiplierFactorNumericType value) {
        this.multiplierFactorNumeric = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the taxCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTITaxCategoryType }
     * 
     * 
     */
    public List<SFTITaxCategoryType> getTaxCategory() {
        if (taxCategory == null) {
            taxCategory = new ArrayList<SFTITaxCategoryType>();
        }
        return this.taxCategory;
    }

    /**
     * Gets the value of the allowanceChargeBaseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAllowanceChargeBaseAmount() {
        return allowanceChargeBaseAmount;
    }

    /**
     * Sets the value of the allowanceChargeBaseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAllowanceChargeBaseAmount(AmountType value) {
        this.allowanceChargeBaseAmount = value;
    }

}
