//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.codelist.paymentmeanscode._1._0.PaymentMeansCodeType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.PaymentDateType;


/**
 * <p>Java class for SFTIPaymentMeansType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIPaymentMeansType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentMeansTypeCode" type="{urn:oasis:names:tc:ubl:codelist:PaymentMeansCode:1:0}PaymentMeansCodeType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}DuePaymentDate" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PayeeFinancialAccount" minOccurs="0"/>
 *         &lt;element name="PayeePartyName" type="{urn:sfti:CommonAggregateComponents:1:0}SFTIPartyNameType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIPaymentMeansType", propOrder = {
    "paymentMeansTypeCode",
    "duePaymentDate",
    "payeeFinancialAccount",
    "payeePartyName"
})
public class SFTIPaymentMeansType {

    @XmlElement(name = "PaymentMeansTypeCode", required = true)
    protected PaymentMeansCodeType paymentMeansTypeCode;
    @XmlElement(name = "DuePaymentDate", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected PaymentDateType duePaymentDate;
    @XmlElement(name = "PayeeFinancialAccount")
    protected SFTIFinancialAccountType payeeFinancialAccount;
    @XmlElement(name = "PayeePartyName")
    protected SFTIPartyNameType payeePartyName;

    /**
     * Gets the value of the paymentMeansTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMeansCodeType }
     *     
     */
    public PaymentMeansCodeType getPaymentMeansTypeCode() {
        return paymentMeansTypeCode;
    }

    /**
     * Sets the value of the paymentMeansTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMeansCodeType }
     *     
     */
    public void setPaymentMeansTypeCode(PaymentMeansCodeType value) {
        this.paymentMeansTypeCode = value;
    }

    /**
     * Gets the value of the duePaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDateType }
     *     
     */
    public PaymentDateType getDuePaymentDate() {
        return duePaymentDate;
    }

    /**
     * Sets the value of the duePaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDateType }
     *     
     */
    public void setDuePaymentDate(PaymentDateType value) {
        this.duePaymentDate = value;
    }

    /**
     * Gets the value of the payeeFinancialAccount property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIFinancialAccountType }
     *     
     */
    public SFTIFinancialAccountType getPayeeFinancialAccount() {
        return payeeFinancialAccount;
    }

    /**
     * Sets the value of the payeeFinancialAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIFinancialAccountType }
     *     
     */
    public void setPayeeFinancialAccount(SFTIFinancialAccountType value) {
        this.payeeFinancialAccount = value;
    }

    /**
     * Gets the value of the payeePartyName property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIPartyNameType }
     *     
     */
    public SFTIPartyNameType getPayeePartyName() {
        return payeePartyName;
    }

    /**
     * Sets the value of the payeePartyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIPartyNameType }
     *     
     */
    public void setPayeePartyName(SFTIPartyNameType value) {
        this.payeePartyName = value;
    }

}
