//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.commonaggregatecomponents._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.AmountType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ChargeIndicatorType;


/**
 * <p>Java class for SFTIInvoiceLineAllowanceCharge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIInvoiceLineAllowanceCharge">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}ChargeIndicator"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}Amount" minOccurs="0"/>
 *         &lt;element name="AllowanceChargeBaseAmount" type="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIInvoiceLineAllowanceCharge", propOrder = {
    "chargeIndicator",
    "amount",
    "allowanceChargeBaseAmount"
})
public class SFTIInvoiceLineAllowanceCharge {

    @XmlElement(name = "ChargeIndicator", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0", required = true)
    protected ChargeIndicatorType chargeIndicator;
    @XmlElement(name = "Amount", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected AmountType amount;
    @XmlElement(name = "AllowanceChargeBaseAmount")
    protected AmountType allowanceChargeBaseAmount;

    /**
     * Gets the value of the chargeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public ChargeIndicatorType getChargeIndicator() {
        return chargeIndicator;
    }

    /**
     * Sets the value of the chargeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public void setChargeIndicator(ChargeIndicatorType value) {
        this.chargeIndicator = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the allowanceChargeBaseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAllowanceChargeBaseAmount() {
        return allowanceChargeBaseAmount;
    }

    /**
     * Sets the value of the allowanceChargeBaseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAllowanceChargeBaseAmount(AmountType value) {
        this.allowanceChargeBaseAmount = value;
    }

}
