//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package oasis.names.tc.ubl.unspecializeddatatypes._1._0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.BuildingNumberType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ConditionType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.CountrySubentityType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.DepartmentType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.DescriptionType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.DistrictType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ExtensionType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.FloorType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.InformationType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.InstructionsType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.LineType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.LocationType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.LossRiskType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.MailType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.NoteType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.PlacardEndorsementType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.PlacardNotationType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.PostboxType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ReasonType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.RegionType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.RoomType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.TelefaxType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.TelephoneType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.TermsType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.TimezoneOffsetType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ValueType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.ZoneType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Component xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns="urn:oasis:names:tc:ubl:UnspecializedDatatypes:1:0" xmlns:cct="urn:oasis:names:tc:ubl:CoreComponentTypes:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;ccts:ComponentType&gt;DT&lt;/ccts:ComponentType&gt;&lt;ccts:DictionaryEntryName&gt;Text. Type&lt;/ccts:DictionaryEntryName&gt;&lt;ccts:RepresentationTerm&gt;Text&lt;/ccts:RepresentationTerm&gt;
 *         &lt;/ccts:Component&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:oasis:names:tc:ubl:CoreComponentTypes:1:0>TextType">
 *       &lt;attribute name="languageID" type="{http://www.w3.org/2001/XMLSchema}language" />
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType")
@XmlSeeAlso({
    ConditionType.class,
    InstructionsType.class,
    RoomType.class,
    InformationType.class,
    ZoneType.class,
    CountrySubentityType.class,
    DistrictType.class,
    MailType.class,
    TelephoneType.class,
    NoteType.class,
    LocationType.class,
    LineType.class,
    TermsType.class,
    TimezoneOffsetType.class,
    ExtensionType.class,
    TelefaxType.class,
    ValueType.class,
    ReasonType.class,
    FloorType.class,
    LossRiskType.class,
    RegionType.class,
    PlacardEndorsementType.class,
    DepartmentType.class,
    PlacardNotationType.class,
    DescriptionType.class,
    PostboxType.class,
    BuildingNumberType.class
})
public class TextType
    extends oasis.names.tc.ubl.corecomponenttypes._1._0.TextType
{


}
