//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package sfti.documents.basicinvoice._1._0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.ubl.codelist.currencycode._1._0.CurrencyCodeType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.IssueDateType;
import oasis.names.tc.ubl.commonbasiccomponents._1._0.NoteType;
import oasis.names.tc.ubl.unspecializeddatatypes._1._0.CodeType;
import sfti.commonaggregatecomponents._1._0.SFTIAllowanceChargeType;
import sfti.commonaggregatecomponents._1._0.SFTIBuyerPartyType;
import sfti.commonaggregatecomponents._1._0.SFTIDeliveryTermsType;
import sfti.commonaggregatecomponents._1._0.SFTIDeliveryType;
import sfti.commonaggregatecomponents._1._0.SFTIDocumentReferenceType;
import sfti.commonaggregatecomponents._1._0.SFTIExchangeRateType;
import sfti.commonaggregatecomponents._1._0.SFTIInvoiceLineType;
import sfti.commonaggregatecomponents._1._0.SFTILegalTotalType;
import sfti.commonaggregatecomponents._1._0.SFTIPaymentMeansType;
import sfti.commonaggregatecomponents._1._0.SFTIPaymentTermsType;
import sfti.commonaggregatecomponents._1._0.SFTIPeriodType;
import sfti.commonaggregatecomponents._1._0.SFTISellerPartyType;
import sfti.commonaggregatecomponents._1._0.SFTISimpleIdentifierType;
import sfti.commonaggregatecomponents._1._0.SFTITaxTotalType;


/**
 * <p>Java class for SFTIInvoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFTIInvoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{urn:sfti:CommonAggregateComponents:1:0}SFTISimpleIdentifierType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}IssueDate"/>
 *         &lt;element name="InvoiceTypeCode" type="{urn:oasis:names:tc:ubl:UnspecializedDatatypes:1:0}CodeType"/>
 *         &lt;element ref="{urn:oasis:names:tc:ubl:CommonBasicComponents:1:0}Note" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:documents:BasicInvoice:1:0}TaxPointDate" minOccurs="0"/>
 *         &lt;element name="InvoiceCurrencyCode" type="{urn:oasis:names:tc:ubl:codelist:CurrencyCode:1:0}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="TaxCurrencyCode" type="{urn:oasis:names:tc:ubl:codelist:CurrencyCode:1:0}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:documents:BasicInvoice:1:0}LineItemCountNumeric"/>
 *         &lt;element ref="{urn:sfti:documents:BasicInvoice:1:0}AdditionalDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}BuyerParty"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}SellerParty"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}Delivery" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PaymentMeans" maxOccurs="3" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}PaymentTerms" minOccurs="0"/>
 *         &lt;element name="AllowanceCharge" type="{urn:sfti:CommonAggregateComponents:1:0}SFTIAllowanceChargeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}ExchangeRate" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}TaxTotal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}LegalTotal"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}InvoiceLine" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:sfti:documents:BasicInvoice:1:0}RequisitionistDocumentReference" maxOccurs="2"/>
 *         &lt;element ref="{urn:sfti:documents:BasicInvoice:1:0}InitialInvoiceDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:sfti:CommonAggregateComponents:1:0}DeliveryTerms" minOccurs="0"/>
 *         &lt;element name="InvoicingPeriod" type="{urn:sfti:CommonAggregateComponents:1:0}SFTIPeriodType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFTIInvoiceType", propOrder = {
    "id",
    "issueDate",
    "invoiceTypeCode",
    "note",
    "taxPointDate",
    "invoiceCurrencyCode",
    "taxCurrencyCode",
    "lineItemCountNumeric",
    "additionalDocumentReference",
    "buyerParty",
    "sellerParty",
    "delivery",
    "paymentMeans",
    "paymentTerms",
    "allowanceCharge",
    "exchangeRate",
    "taxTotal",
    "legalTotal",
    "invoiceLine",
    "requisitionistDocumentReference",
    "initialInvoiceDocumentReference",
    "deliveryTerms",
    "invoicingPeriod"
})
public class SFTIInvoiceType {

    @XmlElement(name = "ID", required = true)
    protected SFTISimpleIdentifierType id;
    @XmlElement(name = "IssueDate", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0", required = true)
    protected IssueDateType issueDate;
    @XmlElement(name = "InvoiceTypeCode", required = true)
    protected CodeType invoiceTypeCode;
    @XmlElement(name = "Note", namespace = "urn:oasis:names:tc:ubl:CommonBasicComponents:1:0")
    protected NoteType note;
    @XmlElement(name = "TaxPointDate")
    protected TaxPointDateType taxPointDate;
    @XmlElement(name = "InvoiceCurrencyCode")
    protected CurrencyCodeType invoiceCurrencyCode;
    @XmlElement(name = "TaxCurrencyCode")
    protected CurrencyCodeType taxCurrencyCode;
    @XmlElement(name = "LineItemCountNumeric", required = true)
    protected LineItemCountNumericType lineItemCountNumeric;
    @XmlElement(name = "AdditionalDocumentReference")
    protected List<SFTIDocumentReferenceType> additionalDocumentReference;
    @XmlElement(name = "BuyerParty", namespace = "urn:sfti:CommonAggregateComponents:1:0", required = true)
    protected SFTIBuyerPartyType buyerParty;
    @XmlElement(name = "SellerParty", namespace = "urn:sfti:CommonAggregateComponents:1:0", required = true)
    protected SFTISellerPartyType sellerParty;
    @XmlElement(name = "Delivery", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected SFTIDeliveryType delivery;
    @XmlElement(name = "PaymentMeans", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected List<SFTIPaymentMeansType> paymentMeans;
    @XmlElement(name = "PaymentTerms", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected SFTIPaymentTermsType paymentTerms;
    @XmlElement(name = "AllowanceCharge")
    protected List<SFTIAllowanceChargeType> allowanceCharge;
    @XmlElement(name = "ExchangeRate", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected SFTIExchangeRateType exchangeRate;
    @XmlElement(name = "TaxTotal", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected List<SFTITaxTotalType> taxTotal;
    @XmlElement(name = "LegalTotal", namespace = "urn:sfti:CommonAggregateComponents:1:0", required = true)
    protected SFTILegalTotalType legalTotal;
    @XmlElement(name = "InvoiceLine", namespace = "urn:sfti:CommonAggregateComponents:1:0", required = true)
    protected List<SFTIInvoiceLineType> invoiceLine;
    @XmlElement(name = "RequisitionistDocumentReference", required = true)
    protected List<SFTIDocumentReferenceType> requisitionistDocumentReference;
    @XmlElement(name = "InitialInvoiceDocumentReference")
    protected List<SFTIDocumentReferenceType> initialInvoiceDocumentReference;
    @XmlElement(name = "DeliveryTerms", namespace = "urn:sfti:CommonAggregateComponents:1:0")
    protected SFTIDeliveryTermsType deliveryTerms;
    @XmlElement(name = "InvoicingPeriod")
    protected SFTIPeriodType invoicingPeriod;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link SFTISimpleIdentifierType }
     *     
     */
    public SFTISimpleIdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTISimpleIdentifierType }
     *     
     */
    public void setID(SFTISimpleIdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link IssueDateType }
     *     
     */
    public IssueDateType getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueDateType }
     *     
     */
    public void setIssueDate(IssueDateType value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the invoiceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getInvoiceTypeCode() {
        return invoiceTypeCode;
    }

    /**
     * Sets the value of the invoiceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setInvoiceTypeCode(CodeType value) {
        this.invoiceTypeCode = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setNote(NoteType value) {
        this.note = value;
    }

    /**
     * Gets the value of the taxPointDate property.
     * 
     * @return
     *     possible object is
     *     {@link TaxPointDateType }
     *     
     */
    public TaxPointDateType getTaxPointDate() {
        return taxPointDate;
    }

    /**
     * Sets the value of the taxPointDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxPointDateType }
     *     
     */
    public void setTaxPointDate(TaxPointDateType value) {
        this.taxPointDate = value;
    }

    /**
     * Gets the value of the invoiceCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getInvoiceCurrencyCode() {
        return invoiceCurrencyCode;
    }

    /**
     * Sets the value of the invoiceCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setInvoiceCurrencyCode(CurrencyCodeType value) {
        this.invoiceCurrencyCode = value;
    }

    /**
     * Gets the value of the taxCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getTaxCurrencyCode() {
        return taxCurrencyCode;
    }

    /**
     * Sets the value of the taxCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setTaxCurrencyCode(CurrencyCodeType value) {
        this.taxCurrencyCode = value;
    }

    /**
     * Gets the value of the lineItemCountNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link LineItemCountNumericType }
     *     
     */
    public LineItemCountNumericType getLineItemCountNumeric() {
        return lineItemCountNumeric;
    }

    /**
     * Sets the value of the lineItemCountNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineItemCountNumericType }
     *     
     */
    public void setLineItemCountNumeric(LineItemCountNumericType value) {
        this.lineItemCountNumeric = value;
    }

    /**
     * Gets the value of the additionalDocumentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalDocumentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalDocumentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIDocumentReferenceType }
     * 
     * 
     */
    public List<SFTIDocumentReferenceType> getAdditionalDocumentReference() {
        if (additionalDocumentReference == null) {
            additionalDocumentReference = new ArrayList<SFTIDocumentReferenceType>();
        }
        return this.additionalDocumentReference;
    }

    /**
     * Gets the value of the buyerParty property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIBuyerPartyType }
     *     
     */
    public SFTIBuyerPartyType getBuyerParty() {
        return buyerParty;
    }

    /**
     * Sets the value of the buyerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIBuyerPartyType }
     *     
     */
    public void setBuyerParty(SFTIBuyerPartyType value) {
        this.buyerParty = value;
    }

    /**
     * Gets the value of the sellerParty property.
     * 
     * @return
     *     possible object is
     *     {@link SFTISellerPartyType }
     *     
     */
    public SFTISellerPartyType getSellerParty() {
        return sellerParty;
    }

    /**
     * Sets the value of the sellerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTISellerPartyType }
     *     
     */
    public void setSellerParty(SFTISellerPartyType value) {
        this.sellerParty = value;
    }

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIDeliveryType }
     *     
     */
    public SFTIDeliveryType getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIDeliveryType }
     *     
     */
    public void setDelivery(SFTIDeliveryType value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the paymentMeans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentMeans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentMeans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIPaymentMeansType }
     * 
     * 
     */
    public List<SFTIPaymentMeansType> getPaymentMeans() {
        if (paymentMeans == null) {
            paymentMeans = new ArrayList<SFTIPaymentMeansType>();
        }
        return this.paymentMeans;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIPaymentTermsType }
     *     
     */
    public SFTIPaymentTermsType getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIPaymentTermsType }
     *     
     */
    public void setPaymentTerms(SFTIPaymentTermsType value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the allowanceCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowanceCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowanceCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIAllowanceChargeType }
     * 
     * 
     */
    public List<SFTIAllowanceChargeType> getAllowanceCharge() {
        if (allowanceCharge == null) {
            allowanceCharge = new ArrayList<SFTIAllowanceChargeType>();
        }
        return this.allowanceCharge;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIExchangeRateType }
     *     
     */
    public SFTIExchangeRateType getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIExchangeRateType }
     *     
     */
    public void setExchangeRate(SFTIExchangeRateType value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the taxTotal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxTotal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTITaxTotalType }
     * 
     * 
     */
    public List<SFTITaxTotalType> getTaxTotal() {
        if (taxTotal == null) {
            taxTotal = new ArrayList<SFTITaxTotalType>();
        }
        return this.taxTotal;
    }

    /**
     * Gets the value of the legalTotal property.
     * 
     * @return
     *     possible object is
     *     {@link SFTILegalTotalType }
     *     
     */
    public SFTILegalTotalType getLegalTotal() {
        return legalTotal;
    }

    /**
     * Sets the value of the legalTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTILegalTotalType }
     *     
     */
    public void setLegalTotal(SFTILegalTotalType value) {
        this.legalTotal = value;
    }

    /**
     * Gets the value of the invoiceLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIInvoiceLineType }
     * 
     * 
     */
    public List<SFTIInvoiceLineType> getInvoiceLine() {
        if (invoiceLine == null) {
            invoiceLine = new ArrayList<SFTIInvoiceLineType>();
        }
        return this.invoiceLine;
    }

    /**
     * Gets the value of the requisitionistDocumentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requisitionistDocumentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequisitionistDocumentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIDocumentReferenceType }
     * 
     * 
     */
    public List<SFTIDocumentReferenceType> getRequisitionistDocumentReference() {
        if (requisitionistDocumentReference == null) {
            requisitionistDocumentReference = new ArrayList<SFTIDocumentReferenceType>();
        }
        return this.requisitionistDocumentReference;
    }

    /**
     * Gets the value of the initialInvoiceDocumentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initialInvoiceDocumentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitialInvoiceDocumentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SFTIDocumentReferenceType }
     * 
     * 
     */
    public List<SFTIDocumentReferenceType> getInitialInvoiceDocumentReference() {
        if (initialInvoiceDocumentReference == null) {
            initialInvoiceDocumentReference = new ArrayList<SFTIDocumentReferenceType>();
        }
        return this.initialInvoiceDocumentReference;
    }

    /**
     * Gets the value of the deliveryTerms property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIDeliveryTermsType }
     *     
     */
    public SFTIDeliveryTermsType getDeliveryTerms() {
        return deliveryTerms;
    }

    /**
     * Sets the value of the deliveryTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIDeliveryTermsType }
     *     
     */
    public void setDeliveryTerms(SFTIDeliveryTermsType value) {
        this.deliveryTerms = value;
    }

    /**
     * Gets the value of the invoicingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link SFTIPeriodType }
     *     
     */
    public SFTIPeriodType getInvoicingPeriod() {
        return invoicingPeriod;
    }

    /**
     * Sets the value of the invoicingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFTIPeriodType }
     *     
     */
    public void setInvoicingPeriod(SFTIPeriodType value) {
        this.invoicingPeriod = value;
    }

}
