//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package oasis.names.tc.ubl.codelist.latitudedirectioncode._1._0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LatitudeDirectionCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LatitudeDirectionCodeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="North"/>
 *     &lt;enumeration value="South"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LatitudeDirectionCodeContentType")
@XmlEnum
public enum LatitudeDirectionCodeContentType {


    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LatitudeDirectionCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;North&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("North")
    NORTH("North"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LatitudeDirectionCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;South&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("South")
    SOUTH("South");
    private final String value;

    LatitudeDirectionCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LatitudeDirectionCodeContentType fromValue(String v) {
        for (LatitudeDirectionCodeContentType c: LatitudeDirectionCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
