//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 06:07:59 em CEST 
//


package oasis.names.tc.ubl.codelist.linestatuscode._1._0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineStatusCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineStatusCodeContentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Added"/>
 *     &lt;enumeration value="Cancelled"/>
 *     &lt;enumeration value="Disputed"/>
 *     &lt;enumeration value="NoStatus"/>
 *     &lt;enumeration value="Revised"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LineStatusCodeContentType")
@XmlEnum
public enum LineStatusCodeContentType {


    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LineStatusCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Line has been added.&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("Added")
    ADDED("Added"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LineStatusCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Line has been cancelled.&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LineStatusCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Line is disputed.&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("Disputed")
    DISPUTED("Disputed"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LineStatusCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Line has no status.&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("NoStatus")
    NO_STATUS("NoStatus"),

    /**
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodeName xmlns="urn:oasis:names:tc:ubl:codelist:LineStatusCode:1:0" xmlns:ccts="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Line has been revised.&lt;/CodeName&gt;
     * </pre>
     * 
     *           
     * 
     */
    @XmlEnumValue("Revised")
    REVISED("Revised");
    private final String value;

    LineStatusCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineStatusCodeContentType fromValue(String v) {
        for (LineStatusCodeContentType c: LineStatusCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
